[tool.poetry]
name = "nephelaiio-tmux"
version = "0.1.0"
description = ""
authors = ["Ted Cook <teodoro.cook@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
netaddr = "^0.8.0"
MarkupSafe = "==2.0.1"
molecule = {extras = ["docker"], version = "^4.0.4"}
ansible-lint = { version = "^6.9.0", markers = "platform_system != 'Windows'" }
yamllint = "^1.28.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
