---
- name: install packages
  package:
    name: "{{ tmux_packages }}"
    state: "{{ tmux_packages_state }}"
  tags:
    - install

- name: create configuration directory
  file:
    dest: "~/{{ tmux_conf_dir }}"
    state: directory
  tags:
    - configure

- name: manage configuration
  template:
    src: "{{ tmux_conf_template }}"
    dest: "~/{{ tmux_conf_file }}"
  tags:
    - configure

- name: manage configuration overrides
  file:
    path: "~/{{ item }}"
    state: absent
  with_items:
    - "{{ tmux_conf_dir }}/tmux_20.conf"
    - "{{ tmux_conf_dir }}/tmux_21.conf"
  tags:
    - configure

- name: create plugin directory
  file:
    dest: "~/{{ tmux_plugin_dir }}"
    state: directory
  tags:
    - configure

- name: install plugins
  git:
    repo: "{{ item['repo'] }}"
    dest: "~/{{ tmux_plugin_dir }}/{{ item['name'] }}"
    version: "{{ item['version'] }}"
    force: yes
  with_items:
    - "{{ tmux_plugins }}"
  tags:
    - configure
