---
- name: Install packages
  ansible.builtin.package:
    name: "{{ tmux_packages }}"
    state: "{{ tmux_packages_state }}"
  tags:
    - install

- name: Create configuration directory
  ansible.builtin.file:
    dest: "~/{{ tmux_conf_dir }}"
    state: directory
  tags:
    - configure

- name: Manage configuration
  ansible.builtin.template:
    src: "{{ tmux_conf_template }}"
    dest: "~/{{ tmux_conf_file }}"
    force: "{{ tmux_conf_force }}"
  tags:
    - configure

- name: Manage configuration overrides
  ansible.builtin.file:
    path: "~/{{ item }}"
    state: absent
  with_items:
    - "{{ tmux_conf_dir }}/tmux_20.conf"
    - "{{ tmux_conf_dir }}/tmux_21.conf"
  tags:
    - configure

- name: Create plugin directory
  ansible.builtin.file:
    dest: "~/{{ tmux_plugin_dir }}"
    state: directory
  tags:
    - configure

- name: Install plugins
  ansible.builtin.git:
    repo: "{{ item['repo'] }}"
    dest: "~/{{ tmux_plugin_dir }}/{{ item['name'] }}"
    version: "{{ item['version'] }}"
    force: yes
  with_items:
    - "{{ tmux_plugins }}"
  tags:
    - configure
