---
- name: Converge

  hosts: all

  pre_tasks:

    - name: update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
      changed_when: false

  roles:
    - role: nephelaiio.tmux
