---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: template
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: false
    pre_build_image: true
    cgroupns_mode: private
    groups:
      - templates
  - name: literal
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: false
    pre_build_image: true
    cgroupns_mode: private
    groups:
      - literals
provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        tmux_conf_file: "~/.tmux.conf"
      literals:
        tmux_conf_literal: |
          # custom config
scenario:
  name: default
verifier:
  name: ansible
