---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: xenial
    image: ubuntu:xenial
  - name: bionic
    image: ubuntu:bionic
  - name: debian9
    image: debian:stretch
  - name: arch
    image: archlinux/base:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
