---
name: Install

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: 'nephelaiio.tmux'

jobs:

  local:
    name: Local install
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.tmux'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install poetry
        run: pip3 install poetry

      - name: Run local install
        run: bash install.sh

      - name: Test tmux binary
        run: tmux -V
